services:
  voicepeak-api:
    image: voicepeak-api
    container_name: voicepeak-api
    ports:
      - "8181:8181"
    platform: linux/amd64
    shm_size: "1g"
    mac_address: ${MAC_ADDRESS}
    hostname: voicepeak-server
